//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chuyende.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
        }
    
        public string MaSP { get; set; }
        public string MaLoaiSP { get; set; }
        public string MaHang { get; set; }
        public string TenSP { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MoTa { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaDau { get; set; }
        public Nullable<int> SoGiam { get; set; }
        public string Chip { get; set; }
        public string Pin { get; set; }
        public string CongSac { get; set; }
        public string HeDieuHanh { get; set; }
        public string DungLuong { get; set; }
        public string Ram { get; set; }
        public string ManHinh { get; set; }
        public string TheSim { get; set; }
        public string CamTruoc { get; set; }
        public string CamSau { get; set; }
        public string Mau { get; set; }
        public string KetNoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual Hang Hang { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
